<form method="POST" action="{{ $action }}" class="card max-w-4xl rounded-[2rem] p-6">
    @csrf
    @if ($method !== 'POST') @method($method) @endif
    <div class="grid gap-5 md:grid-cols-2">
        <label class="md:col-span-2"><span class="text-sm font-black">Perumahan *</span><select name="perumahan_id" required class="mt-2 w-full rounded-2xl border-line px-4 py-3 text-sm focus:border-blue-600 focus:ring-blue-600"><option value="">Pilih Perumahan</option>@foreach($perumahans as $p)<option value="{{ $p->id }}" @selected(old('perumahan_id', $risiko->perumahan_id) == $p->id)>{{ $p->nama }} — {{ $p->kecamatan ?: '-' }}</option>@endforeach</select></label>
        <label><span class="text-sm font-black">Nama Risiko *</span><input name="nama_risiko" required value="{{ old('nama_risiko', $risiko->nama_risiko) }}" class="mt-2 w-full rounded-2xl border-line px-4 py-3 text-sm focus:border-blue-600 focus:ring-blue-600"></label>
        <label><span class="text-sm font-black">Tipe Risiko</span><select id="tipe" name="tipe" class="mt-2 w-full rounded-2xl border-line px-4 py-3 text-sm focus:border-blue-600 focus:ring-blue-600">@foreach(['banjir'=>'Banjir','longsor'=>'Longsor','gempa'=>'Gempa','kebakaran'=>'Kebakaran','angin'=>'Angin Kencang','abrasi'=>'Abrasi','lainnya'=>'Lainnya','__manual__'=>'Manual'] as $value=>$label)<option value="{{ $value }}" @selected(old('tipe', $risiko->tipe) === $value)>{{ $label }}</option>@endforeach</select></label>
        <label id="manual-wrap" class="hidden"><span class="text-sm font-black">Tipe Manual</span><input name="tipe_manual" value="{{ old('tipe_manual') }}" class="mt-2 w-full rounded-2xl border-line px-4 py-3 text-sm focus:border-blue-600 focus:ring-blue-600"></label>
        <label><span class="text-sm font-black">Tingkat *</span><select name="tingkat" required class="mt-2 w-full rounded-2xl border-line px-4 py-3 text-sm focus:border-blue-600 focus:ring-blue-600">@foreach(['rendah'=>'Rendah','sedang'=>'Sedang','tinggi'=>'Tinggi','kritis'=>'Kritis'] as $value=>$label)<option value="{{ $value }}" @selected(old('tingkat', $risiko->tingkat) === $value)>{{ $label }}</option>@endforeach</select></label>
        <label><span class="text-sm font-black">Status Tindak Lanjut</span><input name="status_tindak_lanjut" value="{{ old('status_tindak_lanjut', $risiko->status_tindak_lanjut) }}" placeholder="Contoh: Terpantau / Butuh tindak lanjut" class="mt-2 w-full rounded-2xl border-line px-4 py-3 text-sm focus:border-blue-600 focus:ring-blue-600"></label>
        <label class="md:col-span-2"><span class="text-sm font-black">Deskripsi</span><textarea name="deskripsi" rows="4" class="mt-2 w-full rounded-2xl border-line px-4 py-3 text-sm focus:border-blue-600 focus:ring-blue-600">{{ old('deskripsi', $risiko->deskripsi) }}</textarea></label>
        <label class="md:col-span-2"><span class="text-sm font-black">Mitigasi/Catatan</span><textarea name="mitigasi" rows="3" class="mt-2 w-full rounded-2xl border-line px-4 py-3 text-sm focus:border-blue-600 focus:ring-blue-600">{{ old('mitigasi', $risiko->mitigasi) }}</textarea></label>
    </div>
    <div class="mt-6 flex flex-wrap gap-3"><button class="rounded-full btn-blue px-6 py-3 text-sm font-black">{{ $submit }}</button><a href="{{ route('admin.risikos.index') }}" class="rounded-full border border-line px-6 py-3 text-sm font-black text-slate-600">Batal</a></div>
</form>
@push('scripts')<script>const tipe=document.getElementById('tipe'),wrap=document.getElementById('manual-wrap');function sync(){wrap.classList.toggle('hidden',tipe.value!=='__manual__')}tipe.addEventListener('change',sync);sync();</script>@endpush
